### ISSUE TITLE
Short string ids would be better for 2 reasons

### ISSUE THREAD

**Issue by r1chardj0n3s** [benmoran56/esper#39]
https://github.com/benmoran56/esper/blob/7d30830dbba71416eb059c75262cd1d651b2526e/esper.py#L35

This is mostly a shower thought, but two reasons a well-crafted short string id set would be better:

1. string-based dicts have their own hyper-optimised implementation in CPython (the implementation switches to a "general" dict as soon as you use a non-string key in the dict).
2. short strings constructed of random letters would be shorter than random numbers when displayed in debugging, and potentially could even use very short words / word combinations which could make debugging (displaying and recognising ids in a game UI for example) simpler.

**Comment by benmoran56** [comment]
Hey @r1chardj0n3s, 

Sorry for taking such an incredibly long time to reply. I don't think I've been getting alerts for this repo for some reason :( 

I had no idea that there was a difference in internal implementations for dictionaries. I'll definitely have a look at this.

**Comment by benmoran56** [comment]
I've been thinking about this, and mostly wondering about the performance impact of generating unique (random) string IDs. It's not that CPU intensive, but obviously can add up if you're trying to do a large amount per frame. 

A quick improvement may be just to keep using ints, but just cast them to str? That would continue to be unique, wouldn't cost much overhead on creation, and could then benefit from the optimized dict lookups. It doesn't address point number 2, but might be a quick improvement. 

I'll have to make a benchmark to compare the difference in creation times and lookup times to make sure the results are as expected.

**Comment by benmoran56** [comment]
I forgot to update this, but I did some looking into this a few months back. Turns out there wouldn't really be any performance benefit, since dictionary lookups are actually very uncommon. Most of the time things are cached, so it wasn't really possible to measure any performance increase.  It _was_ actually a tiny bit slower for entity creation, since it take some time to come up with the random strings. 

Maybe there is a faster way to do it. I suppose things like the `uuid` module are never going to be as fast as just `int += 1`. 
Maybe though, the readability improvement is worth the small performance decrease for entity creation? I'll have to do a little bench marking to see just how much of an impact it would have.

**Comment by benmoran56** [comment]
It seems like the performance impact would be not insignificant, so I'm going to close this for the time being. Precious little cpu cycles as it is, and all that :)

On a related note, I have been thinking of a different internal caching method. I'm not sure how heavily it will rely on dictionary lookup, but I'm going to keep this in mind when I start testing that.
