### ISSUE TITLE
try_components

### ISSUE THREAD

**Issue by shezard** [benmoran56/esper#40]
I'm wondering if adding a ```try_components``` would be usefull to anyone.

Usage :
```python
for hp, mp in self.world.try_components(ent, HP, MP):
    hp.value += 10
    mp.value += 10
```

I have a naive implementation running (with ```self.world``` as an ```esper.World```):
```python
   def try_components(self, *args):

        entity = args[0]
        args = args[1:]

        components = []
        for arg in args:
            if not self.world.has_component(entity, arg):
                return []
            else:
                components.append(self.world.component_for_entity(entity, arg))

        return [(*components, )]
```

Any tough / Feedback ?

**Comment by Pebaz** [comment]
Almost!

As you have it currently implemented, it exits early by returning an empty component list to prevent the processing of entities that do not have the collection of requested components.

I think a potential improvement could be to replace components that an entity does *not* have with `None` or `[]`  so that the processing can still continue.

Example:

```python
for hp, mp in self.world.try_components(ent, HP, MP):
    if hp: hp.value += 10
    if mp: mp.value += 10
```

In your reference implementation, you could simply change:

```python
components = []
for arg in args:
    if not self.world.has_component(entity, arg):
        return []
    else:
        components.append(self.world.component_for_entity(entity, arg))
```

To use an existing API function:

```python
components = [self.world.try_component(entity, arg) for arg in args]
```

If such a function were to exist, I'd be interested!

**Comment by benmoran56** [comment]
Hi @shezard, @Pebaz, 

First of all, my apologies for someone missing this issue. As for your idea, I think it's a good one. I'll think about a performant way to implement it. ideally we don't want to call another existing function, due to the performance hit of a function call. It's small, but does add up. 

As for your idea Pebaz, I would lean towards it not returning anything at all if both components don't exist. The main idea of the `try_component` method was to avoid doing a `has_component` call, so having to check if anything was returned from `try_components` sort of defeats the purpose. To that point though, maybe a new `has_components` method is also a good idea.

**Comment by benmoran56** [comment]
Hi @shezard, @Pebaz,

I went ahead and added two new methods:  `has_components` and `try_components`, which operate like you would think. They will work for an arbitrary number of components, such as: 

```
if world.has_components(entity, Life, Body):
   ...
```

and

```
for life, body in world.try_components(Velocity, Position):
   ...
```

I'll see if I can get a new release out in a few days (I have some other tiny cleanups to do as well). Until then, I'll leave this issue open. If you have a chance to try, please let me know if you have any issues.

**Comment by Pebaz** [comment]
I have tried out the new release and all the new methods and they work great!
Thanks for making the change @benmoran56 ! :)
I think this issue should be marked as closed now since the functionality now exists. Any qualms @benmoran56 or @shezard ?

**Comment by benmoran56** [comment]
Great!  I was just leaving this open in case of comments, but I think we can close it now. I've also added unit tests for these new methods to confirm that they're working correctly. 

Thanks for using esper ,and I'm glad you find it useful!
